const navLinks = document.querySelectorAll("header nav a");
const sectionPlaceholders = document.querySelectorAll(".section-placeholder");

// Theme toggle functionality
const themeToggle = document.getElementById('theme-toggle');
const themeIcon = themeToggle.querySelector('i');

// Check for saved theme preference or default to dark mode
const currentTheme = localStorage.getItem('theme') || 'dark';
document.documentElement.setAttribute('data-theme', currentTheme);

// Set initial icon based on theme
if (currentTheme === 'light') {
    themeIcon.className = 'fas fa-sun';
} else {
    themeIcon.className = 'fas fa-moon';
}

// Toggle theme function
function toggleTheme() {
    const currentTheme = document.documentElement.getAttribute('data-theme');
    const newTheme = currentTheme === 'dark' ? 'light' : 'dark';

    document.documentElement.setAttribute('data-theme', newTheme);
    localStorage.setItem('theme', newTheme);

    // Update icon
    if (newTheme === 'light') {
        themeIcon.className = 'fas fa-sun';
    } else {
        themeIcon.className = 'fas fa-moon';
    }
}

// Add event listener to theme toggle button
themeToggle.addEventListener('click', toggleTheme);

function loadSection(id) {
    const placeholder = document.getElementById(id);
    if (!placeholder) return;

    // Clear existing content
    placeholder.innerHTML = '';

    // Load content from file
    fetch(`sections/${id}.html`)
        .then(response => response.text())
        .then(html => {
            placeholder.innerHTML = html;
            // Add active class to the loaded section
            const section = placeholder.querySelector('section');
            if (section) {
                section.classList.add('active-section');
                // Scroll to the top of the loaded section, accounting for fixed navbar
                const navbar = document.querySelector('nav');
                const navbarHeight = navbar.offsetHeight;
                const offsetTop = section.offsetTop - navbarHeight - 20; // 20px padding
                window.scrollTo({ top: offsetTop, behavior: 'smooth' });
            }
        })
        .catch(error => {
            console.error(`Error loading section ${id}:`, error);
            placeholder.innerHTML = `<section id="${id}" class="active-section"><div class="section-header"><h2>Error</h2></div><p>Failed to load content.</p></section>`;
        });
}

function showSection(id) {
    // Hide all sections
    sectionPlaceholders.forEach(placeholder => {
        const section = placeholder.querySelector('section');
        if (section) {
            section.classList.remove("active-section");
        }
    });

    // Load and show the target section
    loadSection(id);
}

navLinks.forEach(link => {
    link.addEventListener("click", e => {
        e.preventDefault();
        const targetId = link.getAttribute("href").substring(1);
        navLinks.forEach(l => l.classList.remove("active"));
        link.classList.add("active");
        showSection(targetId);
        window.history.pushState(null, "", "#" + targetId);
    });
});

window.addEventListener("DOMContentLoaded", () => {
    const hash = window.location.hash.substring(1) || "about";
    const activeLink = document.querySelector(`header nav a[href="#${hash}"]`);
    if (activeLink) activeLink.classList.add("active");
    showSection(hash);
});

window.addEventListener("hashchange", () => {
    const hash = window.location.hash.substring(1);
    showSection(hash);
    navLinks.forEach(l => l.classList.remove("active"));
    const current = document.querySelector(`header nav a[href="#${hash}"]`);
    if (current) current.classList.add("active");
});
/* FUNCTION GENERATOR PROJECT SLIDER */

const slides = [
    
    {
img:"img/Func_output/ckt breaboard.jpeg",
caption:"Breadboard prototype showing frequency generation stage (top board, labelled) and amplitude control stage (bottom board) with oscilloscope probes connected."
},

 {
img:"img/Func_output/veroboard.jpg",
caption:"Final veroboard implementation. The ICL8038 (left IC) and TL072 (right IC) are visible at the centre, with five potentiometers and labelled output leads around the perimeter."
},
 {
img:"img/Func_output/simulation diagram.jpeg",
caption:"Complete Proteus circuit schematic"
},

{
img:"img/Func_output/SQU osc.jpeg",
caption:"Square wave output at 49.98 Hz showing sharp rise and fall transitions. Mild top-tilt arises from AC coupling at low frequency."
},

{
img:"img/Func_output/SINE osc.jpeg",
caption:"Sine wave output: Vpp = 11.2 V, f = 50.03 Hz, Vavg = −707 mV, duty cycle 48.42%."
},

{
img:"img/Func_output/TRI .jpg",
caption:"Triangular Wave Output – Linear rising and falling slopes generated by constant current charging and discharging."
},

{
img:"img/Func_output/amp adj.jpeg",
caption:"Amplitude Adjustment – Output amplitude controlled using the TL082 variable gain amplifier stage."
},
{
img:"img/Func_output/simulation output.jpg",
caption:"Proteus simulation: square wave (top), sine wave (middle), and triangular wave (bottom) generated simultaneously by the ICL8038 at default duty cycle and frequency settings."
},
{
img:"img/Func_output/simu with duty cycle.jpg",
caption:"Simulation with duty cycle shifted from 80%: asymmetric square wave (top) and sawtooth-like triangular wave (bottom) resulting from unequal charge/discharge timing."
}

];

let currentSlide = 0;

function showSlide(index){

currentSlide = (index + slides.length) % slides.length;

document.getElementById("slideImage").src = slides[currentSlide].img;
document.getElementById("slideCaption").innerText = slides[currentSlide].caption;

}

/* OPEN MODAL (works with dynamically loaded sections) */

document.addEventListener("click", function(e){

if(e.target && e.target.id === "openProject"){

document.getElementById("projectModal").style.display = "flex";
showSlide(0);

}

});

/* NEXT / PREV */

document.addEventListener("click", function(e){

if(e.target.classList.contains("next")){
showSlide(currentSlide + 1);
}

if(e.target.classList.contains("prev")){
showSlide(currentSlide - 1);
}

});

/* CLOSE BUTTON */

document.addEventListener("click", function(e){

if(e.target.classList.contains("modal-close")){
document.getElementById("projectModal").style.display = "none";
}

});

/* CLOSE IF CLICK OUTSIDE */

window.onclick = function(e){

const modal = document.getElementById("projectModal");

if(e.target === modal){
modal.style.display = "none";
}

};

